export const confirmOrganizerPrefix = "organizer-confirmation:";
export const forgotOrganizerPasswordPrefix = "forgot-organizer-password:";
export const confirmUserPrefix = "user-confirmation:";
export const developmentUrl = "";
export const productionUrl = "";
export const cookieName = "fiefoe";

export const errors = {
  USER_ALREADY_EXISTS: "USER_ALREADY_EXISTS",
  QUEUE_DOES_NOT_EXIST: "QUEUE_DOES_NOT_EXIST",
  QUEUE_NOT_ACTIVE: "QUEUE_NOT_ACTIVE",
  USER_DOES_NOT_EXIST: "USER_DOES_NOT_EXIST",
  USER_NOT_ENQUEUED: "USER_NOT_ENQUEUED",
  QUEUE_NOT_IN_SERVICE: "QUEUE_NOT_IN_SERVICE",
  ORGANIZER_ALREADY_EXISTS: "ORGANIZER_ALREADY_EXISTS",
  ORGANIZER_DOES_NOT_EXIST: "ORGANIZER_DOES_NOT_EXIST",
  CANNOT_ACCESS_USER: "CANNOT_ACCESS_USER",
  CANNOT_ACCESS_QUEUE: "CANNOT_ACCESS_QUEUE",
  PASSWORD_CHANGE_FAILED: "PASSWORD_CHANGED_FAILED",
  ACCOUNT_CONFIRM_FAILED: "ACCOUNT_CONFIRM_FAILED",
  EMAIL_SEND_FAILED: "EMAIL_SEND_FAILED",
  ORGANIZER_CREATION_FAILED: "ORGANIZER_CREATION_FAILED",
  INCORRECT_PASSWORD: "INCORRECT_PASSWORD",
  ORGANIZER_NOT_VERIFIED: "ORGANIZER_NOT_VERIFIED",
  CANNOT_UPDATE_QUEUE: "CANNOT_UPDATE_QUEUE",
  USER_CONFIRM_FAILED: "USER_CONFIRM_FAILED",
  USER_HAS_NO_PHONE_NUMBER: "USER_HAS_NO_PHONE_NUMBER",
  REQUEST_LIMIT_EXCEEDED: "REQUEST_LIMIT_EXCEEDED"
}
