# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main, production ]
  pull_request:
    branches: [ main, production ]

jobs:
  build:

    runs-on: ${{matrix.os}}
    defaults:
      run:
        working-directory: fulcrum
    env:
      FRONTEND_LOCAL_URL: ${{secrets.FRONTEND_LOCAL_URL}}
      FRONTEND_PROD_URL: ${{secrets.FRONTEND_PROD_URL}}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      REDIS_URL: ${{ secrets.REDIS_URL }}
      NODE_ENV: ${{ secrets.NODE_ENV }}
      SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
      SENDER_EMAIL: ${{secrets.SENDER_EMAIL}}
      SMTP_PASSWORD: ${{secrets.SMTP_PASSWORD}}
      SMTP_SERVER: ${{secrets.SMTP_SERVER}}
      SMTP_USERNAME: ${{secrets.SMTP_USERNAME}}
      TWILIO_ACCOUNT_SID: ${{secrets.TWILIO_ACCOUNT_SID}}
      TWILIO_AUTH_TOKEN: ${{secrets.TWILIO_AUTH_TOKEN}}
      TWILIO_PHONE_NUMBER: ${{secrets.TWILIO_PHONE_NUMBER}}

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        os: [ubuntu-latest]


    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: 'fulcrum/package-lock.json'
    - run: npm ci
      
    - run: npm run build --if-present
    
    - run: npx prisma db push
      
    - run: npm test
      env:
        CI: true
